Correct platform name
When building with `podman-compose` on my Mac, I was seeing the below issue:
```
[2/3] STEP 1/3: FROM docker.io/bluerobotics/blueos-base:v0.0.10 AS downloadBinaries
Trying to pull docker.io/bluerobotics/blueos-base:v0.0.10...
Error: creating build container: choosing an image from manifest list docker://bluerobotics/blueos-base:v0.0.10: no image found in image index for architecture arm64, variant "v8", OS linux

exit code: 125
```

I believe this is because the wrong platform string is provided.